Feat/predefined configs
ubiquity-os/ubiquity-os-plugin-installer pull request #28
Opened 2024-11-22 22:27 UTC by Keyrxng

Resolves https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/22
Requires #25

Changes:

- template selection step
- minimal config: I've copied the org installed config but we could create `minimal-config.yml` in a `marketplace` repo (`.ubiquity-os`?) and just fetch it from there instead
- full defaults: I've implemented the schema provided defaults as best we can right now some plugins need updated (see #27)

QA:

https://github.com/user-attachments/assets/490b4344-144d-4d10-a454-b2e61fffd9a8

2024-11-29 16:04 UTC, rndquu requested changes
On `yarn start` getting the same errors as in [this](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/actions/runs/12077953759/job/33681602211?pr=28) CI run.

Pls fix both failing [build](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/actions/runs/12077953759/job/33681602211?pr=28) and [cypress](https://github.com/ubiquity-os/ubiquity-os-plugin-installer/actions/runs/12077953762/job/33681602212?pr=28) workflows.

2024-12-20 09:51 UTC, Keyrxng commented
@rndquu I can't re-open, would you mind doing it for my PRs in this repo. Sorry for the inactivity, been dealing with a bereavement.

2025-02-06 00:00 UTC, Keyrxng commented
This can be reviewed--I've merged in #30 so maybe after it's merged?

Right now when you select `Full Default` you are prompted to enter the `required` fields (evm private key) which is clean UI. Once the push is made, the configs are expanded and all values are visible. Is this the preferred outcome? Or should it look like [this](https://github.com/ubiquity/onboard.ubq.fi/blob/development/static/types/default-configuration.yml)?

1. Expanded on install let's partners see what is configurable and what everything is currently set to without deep diving all plugins.
2. Minimized on install requires they go investigating plugins or the `Custom` section of the particular plugin they have in mind.

2025-02-06 05:39 UTC, 0x4007 commented
> > [!CAUTION]
> > [universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats
> 
> <!-- UbiquityOS - githubAppJwt - 2074e5f5-cd87-4325-a261-b26f990910d3 - @Keyrxng - https://dash.cloudflare.com/17b9dfa79e16b79dffcb11a66768539c/workers/services/view/ubiquity-os-command-start-stop-development/production/observability/logs?granularity=0&time=%7B%22type%22%3A%22absolute%22%2C%22to%22%3A1738800565708%2C%22from%22%3A1738800445708%7D
> {
>   "message": "[universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats",
>   "name": "Error",
>   "stack": "Error: [universal-github-app-jwt] Private Key is in PKCS#1 format, but only PKCS#8 is supported. See https://github.com/gr2m/universal-github-app-jwt#private-key-formats\n    at getToken (index.js:56578:11)\n    at githubAppJwt (index.js:56627:23)\n    at getAppAuthentication (index.js:56797:37)\n    at hook (index.js:57106:37)\n    at Job.doExecute (index.js:30908:110)\n    at index.js:31585:28"
> }
> -->
> 

This might be related to pull precheck based on converting the pull from draft to ready. 

It also makes sense that we just now started seeing this error because it's a brand new feature. 

@gentlementlegen @Whilefoo rfc

2025-02-06 14:15 UTC, whilefoo commented
> This might be related to pull precheck based on converting the pull from draft to ready.
> 
> It also makes sense that we just now started seeing this error because it's a brand new feature.
> 
> @gentlementlegen @whilefoo rfc

It comes from `command-start-stop` and it was triggered when the PR body was edited so it seems to be the same issue as [here](https://github.com/ubiquity-os-marketplace/command-ask/pull/61#issuecomment-2635139526)

2025-02-12 09:26 UTC, gentlementlegen commented
@Keyrxng Sorry for the noise, this task was chosen for testing the issue with `command-start-stop`.

2025-02-12 09:31 UTC, Keyrxng commented
No worries ty for the heads up

2025-02-16 04:32 UTC, Keyrxng commented
This is good to go in terms of functionality guys we are just waiting for https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/30 to get the 2nd approval needed

2025-02-16 09:07 UTC, gentlementlegen commented
@Keyrxng Would it be better to merge the other one first and rebase here?

2025-02-16 09:10 UTC, Keyrxng commented
@gentlementlegen Yeah for sure

2025-02-20 06:00 UTC, Keyrxng commented
@gentlementlegen this is good to go now bud

2025-02-20 07:33 UTC, gentlementlegen commented on build/esbuild-build.ts
> +import MINIMAL_PREDEFINED_CONFIG from "../static/minimal-predefined.json";
Maybe this should go before `dotenv.config()`

2025-02-20 07:34 UTC, gentlementlegen commented on static/scripts/predefined-configs/template-handler.ts
> +import YAML from "yaml";
I have a feeling that these imports are not properly ordered

2025-02-20 07:34 UTC, gentlementlegen commented on static/scripts/predefined-configs/template-handler.ts
> +    // YAML.stringify({ plugins: [] }).length === 12
```suggestion
```

2025-02-20 07:37 UTC, gentlementlegen commented on static/scripts/rendering/template-selector.ts
> +  kill();
Why using this naming?

2025-02-20 07:50 UTC, Keyrxng commented on static/scripts/rendering/template-selector.ts
> +  kill();
Renamed to `removeToast` instead

2025-02-20 09:02 UTC, gentlementlegen commented
I tried this pull-request and I am very confused. Whatever I select, the same configuration seems to be generated in my repo, from minimal to custom or defaults.

2025-02-20 09:31 UTC, Keyrxng commented
> I tried this pull-request and I am very confused. 

Me too @gentlementlegen lmao. I didn't see you select any other option besides minimal in that video, I figured you selected the wrong recording or something. Thank you for taking the time to show me and the logs that does help a bunch 😂 

Below is a video of selecting both `minimal` and `full-default`. As a bonus it also includes a bug I've raised in #40 regarding undefined params via minimal configs and whether the UI should inject or keep empty, keep minimal or expand.


https://github.com/user-attachments/assets/a5fec344-3875-42cd-ab7e-42c80fe3f686

2025-02-20 09:36 UTC, gentlementlegen commented
@Keyrxng Sorry the file limit is 10 mb which is why the video had to be short. With the 3 options, the generated file has been the same. I can do more videos with these if you need them.

2025-02-20 09:51 UTC, Keyrxng commented
I know I run my clips through `CapCut` quick and easy. I saw @eresdev upload a monster 8min video of something lmao, unit.

Idk what to say mate it's hard because my vid shows that same flow without errors, and the templates are updated each push.

I'm thinking "did you accept the overwrite prompt?", "is it a stale `localStorage` situation?", "Was it after a page refresh or back to back minimal > full default?"

I'm going to see if I can reproduce and I'll get back to you.

2025-02-20 11:51 UTC, gentlementlegen commented
The local storage did trigger weird behaviors but I cleaned it before shooting that video.

2025-02-20 13:14 UTC, Keyrxng commented
I cannot reproduce that issue @gentlementlegen I've tried a bunch of different ways:

`no file > minimal > full (no refresh)`
`no file > full > minimal (no refresh)`
`file > minimal > full (w/ refresh)`
`file > full > default (w/refresh)`

I've made the toasts clearer but I'm not sure how to debug for the problem you mentioned sorry.

2025-02-21 15:40 UTC, rndquu approved these changes
Works fine for my local org.

The main issue is how minimal and full configs are fetched:
1. Minimal is [read](https://github.com/ubq-testing/ubiquity-os-plugin-installer/blob/0225e80e682eb76cf58cd85c565f222b79d03842/static/minimal-predefined.json) from json
2. Full is [loaded](https://github.com/ubq-testing/ubiquity-os-plugin-installer/blob/0225e80e682eb76cf58cd85c565f222b79d03842/static/scripts/predefined-configs/template-handler.ts#L91) from another repo

I actually thought we could somehow dynamically derived a config from the plugin's [manifest.json](https://github.com/ubiquity-os-marketplace/command-start-stop/blob/111e17ddfc94eb3098f7d4de4946fd77875ef33f/manifest.json). I'll add it to a separate github issue.

2025-02-23 11:11 UTC, Keyrxng commented
What do you think we should do here @gentlementlegen considering it worked for rndquu and I also couldn't reproduce it? It feels cheap of me to want the merge but I can't debug what I can't recreate unfortunately.

2025-02-23 11:14 UTC, gentlementlegen commented
@Keyrxng Can be fixed later on, the more we use it the more we will be able to figure this out and reproduce the problem.

2025-02-23 11:14 UTC, gentlementlegen approved these changes

2025-02-23 11:14 UTC, merged